window.OPPORTUNITIES = [
  {
    "id": "1",
    "title": "Horse Sanctuary Farm Volunteer",
    "place": "Brenne",
    "country": "France",
    "region": "Europe",
    "lat": 46.73,
    "lng": 1.21,
    "url": "https://www.workaway.info/en/host/666525329529",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "2",
    "title": "Cat Sanctuary Animal Carer",
    "place": "Kouvaras",
    "country": "Greece",
    "region": "Europe",
    "lat": 37.83,
    "lng": 23.97,
    "url": "https://www.workaway.info/en/host/789819465563",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "3",
    "title": "Animal Sanctuary Volunteer",
    "place": "Paredes de Coura",
    "country": "Portugal",
    "region": "Europe",
    "lat": 41.91,
    "lng": -8.56,
    "url": "https://www.workaway.info/en/host/294954381696",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "4",
    "title": "Vegan Animal Sanctuary Volunteer",
    "place": "Serra da Estrela",
    "country": "Portugal",
    "region": "Europe",
    "lat": 40.32,
    "lng": -7.61,
    "url": "https://www.workaway.info/en/host/827861528924",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "5",
    "title": "Vegan Animal Sanctuary Volunteer",
    "place": "Palmela",
    "country": "Portugal",
    "region": "Europe",
    "lat": 38.57,
    "lng": -8.9,
    "url": "https://www.workaway.info/en/host/619748631243",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "6",
    "title": "Farm Sanctuary Volunteer",
    "place": "Valencia",
    "country": "Spain",
    "region": "Europe",
    "lat": 39.47,
    "lng": -0.38,
    "url": "https://www.workaway.info/en/host/351332648991",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "7",
    "title": "Horse and Animal Sanctuary Volunteer",
    "place": "Atajate",
    "country": "Spain",
    "region": "Europe",
    "lat": 36.64,
    "lng": -5.25,
    "url": "https://www.workaway.info/en/host/745219648925",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "8",
    "title": "Dog and Cat Shelter Volunteer",
    "place": "Los Gallardos",
    "country": "Spain",
    "region": "Europe",
    "lat": 37.17,
    "lng": -1.94,
    "url": "https://paws-patas.org/45641-2",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Not confirmed; check the original listing.",
    "opportunityType": "Volunteering"
  },
  {
    "id": "9",
    "title": "Exotic Animal Sanctuary Volunteer",
    "place": "Erdősmecske",
    "country": "Hungary",
    "region": "Europe",
    "lat": 46.18,
    "lng": 18.51,
    "url": "https://www.workaway.info/en/host/245893947824",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "10",
    "title": "Wildlife Rehabilitation Volunteer",
    "place": "County Cork",
    "country": "Ireland",
    "region": "Europe",
    "lat": 51.9,
    "lng": -8.47,
    "url": "https://www.workaway.info/en/host/172351796966",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "11",
    "title": "Animal Rescue Volunteer",
    "place": "Crete",
    "country": "Greece",
    "region": "Europe",
    "lat": 35.2,
    "lng": 24.9,
    "url": "https://www.workaway.info/en/host/798957627257",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "12",
    "title": "Animal Sanctuary Volunteer",
    "place": "Fokida",
    "country": "Greece",
    "region": "Europe",
    "lat": 38.56,
    "lng": 22.25,
    "url": "https://www.workaway.info/en/host/662187597996",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "13",
    "title": "Animal Welfare Volunteer",
    "place": "Amorgos",
    "country": "Greece",
    "region": "Europe",
    "lat": 36.83,
    "lng": 25.9,
    "url": "https://www.workaway.info/en/host/922241888679",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "14",
    "title": "Dog Rescue Shelter Volunteer",
    "place": "Portugal",
    "country": "Portugal",
    "region": "Europe",
    "lat": 39.6,
    "lng": -8.0,
    "url": "https://www.workaway.info/en/host/386541837946",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "15",
    "title": "Hold Fast To Dreams Animal Sanctuary Farm Volunteer",
    "place": "Pareto",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.52,
    "lng": 8.38,
    "url": "https://www.worldpackers.com/positions/98941",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "16",
    "title": "Animal Sanctuary and Dog Rescue Volunteer",
    "place": "Calatabiano",
    "country": "Italy",
    "region": "Europe",
    "lat": 37.82,
    "lng": 15.23,
    "url": "https://www.worldpackers.com/positions/78078",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "17",
    "title": "Animal Sanctuary Caretaker",
    "place": "Toledo",
    "country": "Spain",
    "region": "Europe",
    "lat": 39.86,
    "lng": -4.03,
    "url": "https://www.worldpackers.com/positions/74257",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "10 days"
  },
  {
    "id": "18",
    "title": "Dog Shelter Volunteer",
    "place": "Bilje",
    "country": "Croatia",
    "region": "Europe",
    "lat": 45.61,
    "lng": 18.74,
    "url": "https://www.worldpackers.com/positions/44450",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "30 days"
  },
  {
    "id": "19",
    "title": "Animal Shelter Volunteer",
    "place": "Kostinbrod",
    "country": "Bulgaria",
    "region": "Europe",
    "lat": 42.82,
    "lng": 23.22,
    "url": "https://www.worldpackers.com/positions/70484",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "20",
    "title": "Wildlife Rescue and Rehabilitation Volunteer",
    "place": "Cyprus",
    "country": "Cyprus",
    "region": "Europe",
    "lat": 35.1,
    "lng": 33.3,
    "url": "https://www.worldpackers.com/positions/101303",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "21",
    "title": "Rescue Sanctuary Growth Volunteer",
    "place": "Modlimowo",
    "country": "Poland",
    "region": "Europe",
    "lat": 53.86,
    "lng": 15.15,
    "url": "https://www.worldpackers.com/positions/102717",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "3 days"
  },
  {
    "id": "22",
    "title": "Dog Shelter and Rural Life Volunteer",
    "place": "Sicily",
    "country": "Italy",
    "region": "Europe",
    "lat": 37.6,
    "lng": 14.0,
    "url": "https://www.worldpackers.com/positions/59403",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "15 days"
  },
  {
    "id": "23",
    "title": "Long-term Animal Rescue Sanctuary Volunteer",
    "place": "Teguise",
    "country": "Spain",
    "region": "Europe",
    "lat": 29.06,
    "lng": -13.56,
    "url": "https://www.worldpackers.com/positions/80436",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "24",
    "title": "Dog Shelter Volunteer",
    "place": "Kalo Chorio",
    "country": "Greece",
    "region": "Europe",
    "lat": 35.12,
    "lng": 25.73,
    "url": "https://www.worldpackers.com/positions/82218",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "25",
    "title": "Horse Rescue Volunteer",
    "place": "Pitovo",
    "country": "Bulgaria",
    "region": "Europe",
    "lat": 42.4,
    "lng": 26.12,
    "url": "https://www.worldpackers.com/positions/95788",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "unverified",
    "lastChecked": null,
    "availabilityNote": "Original listing redirects to a general search page; availability could not be verified.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange"
  },
  {
    "id": "26",
    "title": "Dog Rescue Volunteer",
    "place": "Estoi",
    "country": "Portugal",
    "region": "Europe",
    "lat": 37.09,
    "lng": -7.89,
    "url": "https://www.worldpackers.com/positions/97556",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "27",
    "title": "Baby Bird Wildlife Rescue Volunteer",
    "place": "Gerena",
    "country": "Spain",
    "region": "Europe",
    "lat": 37.53,
    "lng": -6.15,
    "url": "https://www.worldpackers.com/positions/107983",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 weeks"
  },
  {
    "id": "28",
    "title": "Horse and Animal Sanctuary Volunteer",
    "place": "Sardinia",
    "country": "Italy",
    "region": "Europe",
    "lat": 40.0,
    "lng": 9.0,
    "url": "https://www.workaway.info/en/host/267125559795",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 1 month"
  },
  {
    "id": "29",
    "title": "Animal Sanctuary Volunteer",
    "place": "Dordogne",
    "country": "France",
    "region": "Europe",
    "lat": 45.1,
    "lng": 0.7,
    "url": "https://www.workaway.info/en/host/688458957481",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 1 month"
  },
  {
    "id": "30",
    "title": "Dogs Cats and Goats Shelter Volunteer",
    "place": "Nea Kallikratia",
    "country": "Greece",
    "region": "Europe",
    "lat": 40.31,
    "lng": 23.06,
    "url": "https://helpstay.com/stays/Dogs-Cats-Goats-Shelter-Greece/",
    "platform": "HelpStay",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange"
  },
  {
    "id": "31",
    "title": "Animal Refuge Volunteer",
    "place": "Vila do Bispo",
    "country": "Portugal",
    "region": "Europe",
    "lat": 37.08,
    "lng": -8.91,
    "url": "https://helpx.net/host/1449631IP",
    "platform": "HelpX",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "unverified",
    "lastChecked": null,
    "availabilityNote": "Source content could not be read during this refresh; availability is unverified.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange"
  },
  {
    "id": "32",
    "title": "Rescued Farm Animal Sanctuary Volunteer",
    "place": "Greyton",
    "country": "South Africa",
    "region": "Africa",
    "lat": -34.05,
    "lng": 19.61,
    "url": "https://www.workaway.info/en/host/231589594444",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "33",
    "title": "Cat Sanctuary Volunteer",
    "place": "Western Cape",
    "country": "South Africa",
    "region": "Africa",
    "lat": -33.5,
    "lng": 20.0,
    "url": "https://www.workaway.info/en/host/148982731894",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "34",
    "title": "Rescue Dogs in the South African Bush",
    "place": "Hoedspruit",
    "country": "South Africa",
    "region": "Africa",
    "lat": -24.35,
    "lng": 30.95,
    "url": "https://www.worldpackers.com/positions/85228",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "3 weeks"
  },
  {
    "id": "35",
    "title": "Wildlife Orphanage Volunteer",
    "place": "Chingola",
    "country": "Zambia",
    "region": "Africa",
    "lat": -12.53,
    "lng": 27.85,
    "url": "https://www.chimfunshi.de/freiwilligenprogramm/",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Not confirmed; check the original listing.",
    "opportunityType": "Volunteering"
  },
  {
    "id": "36",
    "title": "Ubuntu Wildlife Sanctuary Volunteer",
    "place": "Oudtshoorn",
    "country": "South Africa",
    "region": "Africa",
    "lat": -33.59,
    "lng": 22.2,
    "url": "https://www.worldpackers.com/positions/101911",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "37",
    "title": "Wildlife Rehabilitation and Captive Care Experience",
    "place": "Windhoek",
    "country": "Namibia",
    "region": "Africa",
    "lat": -22.56,
    "lng": 17.08,
    "url": "https://www.naankuse.com/education-wildlife-rehabilitation-and-captive-care-experience",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "An educational programme offered seasonally; confirm current dates and practical duties with Naankuse.",
    "fees": "Not confirmed; check the original listing.",
    "opportunityType": "Conservation education experience",
    "minimumStay": "10-day programme"
  },
  {
    "id": "38",
    "title": "Animal Sanctuary Volunteer",
    "place": "Khon Kaen",
    "country": "Thailand",
    "region": "Asia",
    "lat": 16.44,
    "lng": 102.84,
    "url": "https://www.workaway.info/en/host/397561534819",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "39",
    "title": "Dog and Cat Sanctuary Volunteer",
    "place": "Ko Samui",
    "country": "Thailand",
    "region": "Asia",
    "lat": 9.51,
    "lng": 100.01,
    "url": "https://www.workaway.info/en/host/169925539197",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "At least 5 weeks",
    "accommodation": "Accommodation offered; meals are not provided."
  },
  {
    "id": "40",
    "title": "Help Care for 500+ Rescued Dogs and Cats",
    "place": "Koh Samui",
    "country": "Thailand",
    "region": "Asia",
    "lat": 9.51,
    "lng": 100.01,
    "url": "https://www.worldpackers.com/positions/112844",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "41",
    "title": "Animal Rescue Centre Volunteer",
    "place": "Sattahip",
    "country": "Thailand",
    "region": "Asia",
    "lat": 12.67,
    "lng": 100.9,
    "url": "https://www.workaway.info/en/host/929163234384",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "42",
    "title": "Dog Rescue Shelter Volunteer",
    "place": "Maephim",
    "country": "Thailand",
    "region": "Asia",
    "lat": 12.65,
    "lng": 101.62,
    "url": "https://www.worldpackers.com/positions/67066",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "43",
    "title": "Stray Dog Care Volunteer",
    "place": "Chanthaburi",
    "country": "Thailand",
    "region": "Asia",
    "lat": 12.61,
    "lng": 102.1,
    "url": "https://www.worldpackers.com/positions/68134",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "3 weeks"
  },
  {
    "id": "44",
    "title": "Animal Care and Sanctuary Volunteer",
    "place": "Mueang Tak",
    "country": "Thailand",
    "region": "Asia",
    "lat": 16.88,
    "lng": 99.13,
    "url": "https://www.worldpackers.com/positions/95023",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host lists THB 450 per night including room and meals; platform membership also applies. Confirm current rate.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week",
    "alternateSources": [
      {
        "url": "https://www.worldpackers.com/positions/101962",
        "label": "Additional animal-care role at the same host"
      }
    ]
  },
  {
    "id": "46",
    "title": "Soi Dog Foundation Volunteer",
    "place": "Phuket",
    "country": "Thailand",
    "region": "Asia",
    "lat": 7.95,
    "lng": 98.34,
    "url": "https://www.soidog.org/volunteer",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Not confirmed; check the original listing.",
    "opportunityType": "Volunteering",
    "minimumStay": "2 days for new volunteers"
  },
  {
    "id": "47",
    "title": "Animal Sanctuary and Clinic Volunteer",
    "place": "Sangkhlaburi",
    "country": "Thailand",
    "region": "Asia",
    "lat": 15.15,
    "lng": 98.45,
    "url": "https://helpstay.com/stays/animal-sanctuary-volunteering",
    "platform": "HelpStay",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange"
  },
  {
    "id": "48",
    "title": "Animal Shelter Volunteer",
    "place": "Kerala",
    "country": "India",
    "region": "Asia",
    "lat": 10.4,
    "lng": 76.3,
    "url": "https://www.workaway.info/en/host/253489288159",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "49",
    "title": "Disabled and Vulnerable Animal Care Volunteer",
    "place": "Siem Reap",
    "country": "Cambodia",
    "region": "Asia",
    "lat": 13.36,
    "lng": 103.86,
    "url": "https://www.workaway.info/en/host/894961447845",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 1 month"
  },
  {
    "id": "51",
    "title": "Cikananga Wildlife Center Volunteer",
    "place": "Sukabumi",
    "country": "Indonesia",
    "region": "Asia",
    "lat": -6.93,
    "lng": 106.93,
    "url": "https://www.wanicare.com/en-EU/internships-and-volunteers/",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "2026 international volunteer/intern fees: EUR 125–165 per week; confirm current programme and rate.",
    "opportunityType": "Volunteering",
    "accommodation": "Accommodation and two meals per day included in the programme fee."
  },
  {
    "id": "52",
    "title": "Animal Rescue Experience",
    "place": "Bandaragama",
    "country": "Sri Lanka",
    "region": "Asia",
    "lat": 6.71,
    "lng": 79.99,
    "url": "https://www.worldpackers.com/positions/105378",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "53",
    "title": "Dog Sanctuary Volunteer",
    "place": "Langkawi",
    "country": "Malaysia",
    "region": "Asia",
    "lat": 6.35,
    "lng": 99.8,
    "url": "https://www.worldpackers.com/positions/93217",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "54",
    "title": "Animal Sanctuary Volunteer",
    "place": "Lalitpur",
    "country": "Nepal",
    "region": "Asia",
    "lat": 27.67,
    "lng": 85.32,
    "url": "https://www.worldpackers.com/positions/8306",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "55",
    "title": "Vegan Animal Sanctuary Volunteer",
    "place": "Rawang",
    "country": "Malaysia",
    "region": "Asia",
    "lat": 3.32,
    "lng": 101.58,
    "url": "https://www.workaway.info/en/host/291467997484",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "56",
    "title": "Animal Shelter Care Volunteer",
    "place": "Kalibo",
    "country": "Philippines",
    "region": "Asia",
    "lat": 11.7,
    "lng": 122.36,
    "url": "https://www.worldpackers.com/positions/83673",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "57",
    "title": "Dog Sanctuary Rescue Volunteer",
    "place": "Galle",
    "country": "Sri Lanka",
    "region": "Asia",
    "lat": 6.03,
    "lng": 80.22,
    "url": "https://www.volunteerworld.com/en/volunteer-program/dog-sanctuary-rescue-in-sri-lanka-galle",
    "platform": "Volunteer World",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Participation fee required; price depends on dates and duration.",
    "opportunityType": "Fee-based volunteering"
  },
  {
    "id": "58",
    "title": "Animal Shelter Care Support Volunteer",
    "place": "Palawan",
    "country": "Philippines",
    "region": "Asia",
    "lat": 9.8,
    "lng": 118.7,
    "url": "https://www.volunteerworld.com/en/volunteer-program/animal-shelter-care-support-in-philippines-palawan",
    "platform": "Volunteer World",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Participation fee required; price depends on dates and duration.",
    "opportunityType": "Fee-based volunteering"
  },
  {
    "id": "59",
    "title": "Wildlife Rehabilitation Center Volunteer",
    "place": "Rurrenabaque",
    "country": "Bolivia",
    "region": "Americas",
    "lat": -14.44,
    "lng": -67.53,
    "url": "https://www.workaway.info/en/host/885559471382",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "60",
    "title": "Jacj Cuisi Wildlife Sanctuary Volunteer",
    "place": "Rurrenabaque",
    "country": "Bolivia",
    "region": "Americas",
    "lat": -14.44,
    "lng": -67.53,
    "url": "https://www.intiwarayassi.org/volunteering/volunteering-at-parque-jacj-cuisi/",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Volunteer contribution required; payment on arrival. See source for current rates.",
    "opportunityType": "Fee-based volunteering",
    "accommodation": "Shared dormitory and meals on working days."
  },
  {
    "id": "61",
    "title": "amaZOOnico Wildlife Rescue Volunteer",
    "place": "Tena",
    "country": "Ecuador",
    "region": "Americas",
    "lat": -0.99,
    "lng": -77.81,
    "url": "https://www.amazoonicorescue.org/volunteer",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Programme fee required; depends on length of stay.",
    "opportunityType": "Fee-based volunteering",
    "minimumStay": "4 weeks",
    "accommodation": "Food and lodging included in the programme fee."
  },
  {
    "id": "62",
    "title": "Yanacocha Wildlife Rescue Volunteer",
    "place": "Puyo",
    "country": "Ecuador",
    "region": "Americas",
    "lat": -1.49,
    "lng": -78.0,
    "url": "https://yanacocharescue.com/volunteering-yanacocha-rescue-center/",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Programme fee required; confirm current price.",
    "opportunityType": "Fee-based volunteering",
    "accommodation": "Accommodation and meals included in the programme fee."
  },
  {
    "id": "63",
    "title": "Sacha Yacu Wild Animal Rescue Volunteer",
    "place": "Ecuador Amazon",
    "country": "Ecuador",
    "region": "Americas",
    "lat": -1.5,
    "lng": -77.0,
    "url": "https://www.worldpackers.com/positions/106665",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "64",
    "title": "Wildlife Care Volunteer",
    "place": "Amazon Peru",
    "country": "Peru",
    "region": "Americas",
    "lat": -5.0,
    "lng": -74.0,
    "url": "https://www.worldpackers.com/positions/95854",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "65",
    "title": "Animal Rescue Volunteer",
    "place": "Huanchaco",
    "country": "Peru",
    "region": "Americas",
    "lat": -8.08,
    "lng": -79.12,
    "url": "https://www.worldpackers.com/positions/34833",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "unverified",
    "lastChecked": null,
    "availabilityNote": "Original listing redirects to a general search page; availability could not be verified.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange"
  },
  {
    "id": "66",
    "title": "Wildlife Sanctuary and Rehabilitation Volunteer",
    "place": "Alajuela",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 10.02,
    "lng": -84.21,
    "url": "https://www.worldpackers.com/positions/59767",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "67",
    "title": "Wildlife Rescue Center Volunteer",
    "place": "Costa Rica",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 9.95,
    "lng": -84.1,
    "url": "https://www.worldpackers.com/positions/107216",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "68",
    "title": "Rescued Dogs Beach Shelter Volunteer",
    "place": "Samara",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 9.88,
    "lng": -85.53,
    "url": "https://www.worldpackers.com/positions/97206",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "69",
    "title": "Horse Rescue Sanctuary Volunteer",
    "place": "Diriomo",
    "country": "Nicaragua",
    "region": "Americas",
    "lat": 11.88,
    "lng": -86.05,
    "url": "https://www.workaway.info/en/host/543976144148",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "70",
    "title": "Wildlife Sanctuary Volunteer",
    "place": "Nosara",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 9.98,
    "lng": -85.65,
    "url": "https://www.workaway.info/en/host/252357334278",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "71",
    "title": "Rescued Farm Animal Sanctuary Volunteer",
    "place": "Melipilla",
    "country": "Chile",
    "region": "Americas",
    "lat": -33.69,
    "lng": -71.22,
    "url": "https://www.workaway.info/en/host/811696672439",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "72",
    "title": "Equine and Animal Sanctuary Volunteer",
    "place": "Punilla",
    "country": "Argentina",
    "region": "Americas",
    "lat": -31.25,
    "lng": -64.48,
    "url": "https://www.worldpackers.com/positions/64045",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "30 days"
  },
  {
    "id": "73",
    "title": "Wildlife and Dog Shelter Volunteer",
    "place": "Bucaramanga",
    "country": "Colombia",
    "region": "Americas",
    "lat": 7.12,
    "lng": -73.12,
    "url": "https://www.worldpackers.com/positions/109137",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "4 days"
  },
  {
    "id": "74",
    "title": "Animal Rescue Assistance Volunteer",
    "place": "Dominican Republic",
    "country": "Dominican Republic",
    "region": "Americas",
    "lat": 19.0,
    "lng": -70.67,
    "url": "https://www.worldpackers.com/positions/98541",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "75",
    "title": "Farm Animal Sanctuary Volunteer",
    "place": "Krestova",
    "country": "Canada",
    "region": "Americas",
    "lat": 49.45,
    "lng": -117.55,
    "url": "https://www.workaway.info/en/host/276128368564",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "76",
    "title": "Rescue Horse Care Volunteer",
    "place": "Mountain View County",
    "country": "Canada",
    "region": "Americas",
    "lat": 51.65,
    "lng": -114.15,
    "url": "https://www.worldpackers.com/positions/98032",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "77",
    "title": "Animal Rescue Charity Volunteer",
    "place": "Picayune",
    "country": "United States",
    "region": "Americas",
    "lat": 30.53,
    "lng": -89.68,
    "url": "https://www.workaway.info/en/host/173753349614",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least a week"
  },
  {
    "id": "78",
    "title": "Rescued Farm and Domestic Animal Sanctuary",
    "place": "Berkshires",
    "country": "United States",
    "region": "Americas",
    "lat": 42.4,
    "lng": -73.2,
    "url": "https://www.workaway.info/en/host/426315396361",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "79",
    "title": "Non-Profit Animal Sanctuary Volunteer",
    "place": "Kealakekua",
    "country": "United States",
    "region": "Americas",
    "lat": 19.52,
    "lng": -155.92,
    "url": "https://www.workaway.info/en/host/517197735583",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "80",
    "title": "Wildlife Rehabilitation Center Volunteer",
    "place": "St-Henri",
    "country": "Canada",
    "region": "Americas",
    "lat": 46.69,
    "lng": -71.07,
    "url": "https://www.workaway.info/en/host/951318835715",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 3 weeks"
  },
  {
    "id": "81",
    "title": "Wildlife Reserve Volunteer",
    "place": "Naranjito",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 9.47,
    "lng": -84.1,
    "url": "https://www.workaway.info/en/host/336248177964",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "82",
    "title": "Animal Caretaker and Maintenance Volunteer",
    "place": "Tecate",
    "country": "Mexico",
    "region": "Americas",
    "lat": 32.57,
    "lng": -116.63,
    "url": "https://www.worldpackers.com/positions/79287",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "2 weeks"
  },
  {
    "id": "83",
    "title": "Wildlife Rescue Center Volunteer",
    "place": "Maynas",
    "country": "Peru",
    "region": "Americas",
    "lat": -3.75,
    "lng": -73.25,
    "url": "https://www.worldpackers.com/positions/65895",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host participation fee required, in addition to platform membership; see source for current amount.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 week"
  },
  {
    "id": "84",
    "title": "Wildlife Rescue and Rehabilitation Volunteer",
    "place": "Santa Ana",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 9.93,
    "lng": -84.18,
    "url": "https://en.refugioanimalcr.com/voluntariado-1",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Programme fee required. Source gives conflicting daily rates; request a current quote.",
    "opportunityType": "Fee-based volunteering",
    "minimumStay": "1 week"
  },
  {
    "id": "85",
    "title": "Animal Rescue Sanctuary Support Volunteer",
    "place": "Guayabo de Bagaces",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 10.7,
    "lng": -85.23,
    "url": "https://www.volunteerworld.com/en/volunteer-program/animal-rescue-sanctuary-support-in-costa-rica-guayabo-de-bagaces",
    "platform": "Volunteer World",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Participation fee required; price depends on dates and duration.",
    "opportunityType": "Fee-based volunteering"
  },
  {
    "id": "86",
    "title": "Magical Creatures Sanctuary Live-In Internship",
    "place": "Laupahoehoe, Hawaii",
    "country": "United States",
    "region": "Americas",
    "lat": 19.99,
    "lng": -155.24,
    "url": "https://www.helpstay.com/stays/Internships-Work-Trade-Sanctuary-Hawaii",
    "platform": "HelpStay",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Animal-care internship",
    "minimumStay": "Description asks for 3 months; calendar says 1 month. Confirm with host."
  },
  {
    "id": "87",
    "title": "Live-In Animal Care Work-Exchange",
    "place": "Otaki",
    "country": "New Zealand",
    "region": "Oceania",
    "lat": -40.76,
    "lng": 175.15,
    "url": "https://www.theblacksheep.org.nz/join-our-crew.html",
    "platform": "Host website",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Not confirmed; check the original listing.",
    "opportunityType": "Volunteering",
    "minimumStay": "6 weeks–3 months for work exchange; at least 3 months for internships",
    "accommodation": "Food and accommodation in exchange for 5–6 hours of work per day (work-exchange option)."
  },
  {
    "id": "88",
    "title": "Farm Animal Sanctuary Volunteer",
    "place": "Manar NSW",
    "country": "Australia",
    "region": "Oceania",
    "lat": -35.28,
    "lng": 149.7,
    "url": "https://www.workaway.info/en/host/399672849554",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "1 month or more"
  },
  {
    "id": "89",
    "title": "Farm Animal Rescue Sanctuary Volunteer",
    "place": "Baw Baw Shire",
    "country": "Australia",
    "region": "Oceania",
    "lat": -37.94,
    "lng": 146.15,
    "url": "https://www.worldpackers.com/positions/114612",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "30 days"
  },
  {
    "id": "90",
    "title": "Kangaroo and Wildlife Sanctuary Volunteer",
    "place": "Northern Territory",
    "country": "Australia",
    "region": "Oceania",
    "lat": -19.5,
    "lng": 133.5,
    "url": "https://www.workaway.info/en/host/5569388784b2",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "lastChecked": "2026-10-06",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "fees": "Host fees not confirmed; platform membership may apply.",
    "opportunityType": "Volunteer / work exchange",
    "minimumStay": "at least 2 weeks"
  },
  {
    "id": "91",
    "title": "Beara Farm Animal Sanctuary Volunteer",
    "place": "Beara Peninsula, County Cork",
    "country": "Ireland",
    "region": "Europe",
    "lat": 51.72,
    "lng": -9.85,
    "url": "https://www.workaway.info/en/host/399657593621",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Work exchange",
    "summary": "Help feed and groom rescued animals, clean shelters and maintain the sanctuary. Host requests confident animal handling and fluent English.",
    "fees": "Host fees not confirmed; Workaway membership may apply.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "At least 2 weeks",
    "accommodation": "Room in the host home; confirm meal arrangements."
  },
  {
    "id": "92",
    "title": "Catalonia Animal Sanctuary Volunteer",
    "place": "Catalonia",
    "country": "Spain",
    "region": "Europe",
    "lat": 41.88,
    "lng": 2.24,
    "url": "https://www.workaway.info/en/host/439976256191",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Work exchange",
    "summary": "Support daily animal care and sanctuary maintenance at a vegan sanctuary in rural Catalonia.",
    "fees": "Host fees not confirmed; Workaway membership may apply.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "At least 2 weeks",
    "accommodation": "Shared accommodation."
  },
  {
    "id": "93",
    "title": "Tenerife Sanctuary Animal-Care Volunteer",
    "place": "Tenerife",
    "country": "Spain",
    "region": "Europe",
    "lat": 28.29,
    "lng": -16.63,
    "url": "https://www.workaway.info/en/host/937426493497",
    "platform": "Workaway",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Work exchange",
    "summary": "Help a registered animal charity with animal welfare and daily sanctuary tasks. Longer commitments are requested for direct animal-care roles.",
    "fees": "Food and accommodation exchanged for help; Workaway membership may apply.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "Usually 3 months or more for animal-care roles",
    "accommodation": "Basic shared community accommodation and food."
  },
  {
    "id": "94",
    "title": "Rescued Dog and Cat Sanctuary Volunteer",
    "place": "San Carlos",
    "country": "Costa Rica",
    "region": "Americas",
    "lat": 10.32,
    "lng": -84.43,
    "url": "https://www.worldpackers.com/positions/113832",
    "platform": "Worldpackers",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based volunteering",
    "summary": "Support rescued dogs and cats through cleaning, walking, socialisation and related sanctuary tasks. Listing specifies about 25 hours of help weekly.",
    "fees": "USD 10 per day contribution; Worldpackers membership also applies.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "1 week",
    "accommodation": "Shared dormitory; lunch listed as included."
  },
  {
    "id": "95",
    "title": "African Wildlife Orphanage Volunteer",
    "place": "Bulawayo",
    "country": "Zimbabwe",
    "region": "Africa",
    "lat": -20.15,
    "lng": 28.58,
    "url": "https://www.goeco.org/area/volunteer-in-africa/zimbabwe/african-wildlife-orphanage/",
    "platform": "GoEco",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based volunteering",
    "summary": "Assist with wildlife food preparation, enclosure cleaning and rehabilitation support at a wildlife orphanage. Duties depend on the animals and staff needs.",
    "fees": "Programme fee required; obtain a current quote.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "2–12 weeks",
    "accommodation": "Shared housing and three meals daily included in programme fee."
  },
  {
    "id": "96",
    "title": "Wildlife Rescue Veterinary Internship",
    "place": "Lilongwe",
    "country": "Malawi",
    "region": "Africa",
    "lat": -13.96,
    "lng": 33.79,
    "url": "https://www.goeco.org/area/volunteer-in-africa/malawi/wildlife-rescue-center-veterinary-internship/",
    "platform": "GoEco",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based veterinary internship",
    "summary": "For currently enrolled veterinary students. Support wildlife husbandry, rehabilitation and supervised clinical work when needed; clinical procedures are not guaranteed daily.",
    "fees": "Programme fee required; optional veterinary courses cost extra.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "2–12 weeks",
    "accommodation": "Shared on-site accommodation and meals included in programme fee."
  },
  {
    "id": "97",
    "title": "Giant Tortoise Conservation Volunteer",
    "place": "Galápagos Islands",
    "country": "Ecuador",
    "region": "Americas",
    "lat": -0.75,
    "lng": -90.5,
    "url": "https://www.goabroad.com/providers/ioi-abroad/programs/galapagos-tortoise-breeding-center-127339",
    "platform": "GoAbroad",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based volunteering",
    "summary": "Join IOI’s tortoise conservation placement to support care, growth monitoring and visitor education. Basic to intermediate Spanish is requested.",
    "fees": "Contact IOI for programme costs and current terms.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "See provider for available durations"
  },
  {
    "id": "98",
    "title": "Moholoholo Wildlife Rehabilitation Volunteer",
    "place": "Hoedspruit",
    "country": "South Africa",
    "region": "Africa",
    "lat": -24.35,
    "lng": 30.95,
    "url": "https://www.goabroad.com/providers/african-conservation-experience/programs/moholoholo-wildlife-rehabilitation-centre-52509",
    "platform": "GoAbroad",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based volunteering",
    "summary": "African Conservation Experience placement supporting rescued wildlife through food preparation, enrichment and rehabilitation-centre tasks.",
    "fees": "Programme fee required; contact provider for a quote.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "Year-round programme; confirm dates",
    "accommodation": "Dormitory or group accommodation listed."
  },
  {
    "id": "99",
    "title": "Almeirim Animal Rescue Caretaker",
    "place": "Almeirim",
    "country": "Portugal",
    "region": "Europe",
    "lat": 39.21,
    "lng": -8.63,
    "url": "https://www.volunteerworld.com/en/volunteer-program/animal-rescue-caretaker-in-portugal-almeirim",
    "platform": "Volunteer World",
    "postedDate": null,
    "locationPrecision": "Approximate town or region, not an exact site address",
    "opportunityType": "Fee-based volunteering",
    "summary": "Care for rescued domestic animals through feeding, cleaning, enrichment and sanctuary maintenance. Published programme dates extend into late 2026.",
    "fees": "Participation fee required; check selected dates for the current price.",
    "firstSeen": "2026-10-06",
    "lastChecked": "2026-10-06",
    "lastCheckAttempt": "2026-10-06",
    "sourceStatus": "page_checked",
    "availabilityNote": "Source page checked; confirm dates and availability with the host.",
    "minimumStay": "2–12 weeks",
    "accommodation": "Shared volunteer house; self-prepared meals."
  }
];
